import parseInput from "./parse-input.ts";
import stylize, { type ProcessedToken } from "./stylize.ts";
import {
  createCliRenderer,
  Box,
  Text,
  type ProxiedVNode,
  Select,
  ScrollBox,
  TextTableRenderable,
  type TextTableCellContent,
} from "@opentui/core";
import { parseArgs } from "node:util";
import got from "got";
import { Chalk } from "chalk";
import * as fs from "node:fs/promises";

const chalk = new Chalk();

const args = parseArgs({
  args: Bun.argv,
  options: {
    renderImages: {
      type: "boolean",
      default: true,
    },
    width: {
      type: "string",
      default: process.env.COLUMNS || "80",
    },
  },
  allowPositionals: true,
  allowNegative: true,
});

function renderTable(tableTokens: ProcessedToken) {
  const rows = [];
  for (const row of tableTokens.content) {
    const rowTokens = [];
    for (const cell of row.content) {
      if (cell.type !== "table-cell") {
        throw new Error(
          chalk.red.bold(`Cell type was ${cell.type} instead of "table-cell"!`),
        );
      }
      const cells = [];
      for (const item of cell.content) {
        let cellText = "";
        if (item.type === "text") {
          if (typeof item.content !== "string") {
            throw new Error(
              chalk.red.bold(
                `The type of the table cell content was ${typeof item.content} instead of string!`,
              ),
            );
          }
          cellText += item.content;
        } else if (item.type === "image") {
          cellText += item.content.render();
        } else {
          throw new Error(
            chalk.red.bold(
              `Type not recognized: expected "text" or "image" but got ${item.type}`,
            ),
          );
        }
        cells.push(cellText);
      }
      rowTokens.push(cells);
    }
    rows.push(rowTokens);
  }
}

export async function renderMarkdown(filePath: string) {
  let fileContent: string = "";
  const componentArray: (ProxiedVNode<any> | TextTableRenderable)[] = [];
  if (URL.canParse(filePath)) {
    fileContent = await got(filePath).text();
  } else {
    try {
      fileContent = await Bun.file(filePath).text();
    } catch (err) {
      throw new Error(chalk.red(`Encountered an error: ${err}`));
    }
  }
  const stylizedTokens: ProcessedToken[] = await stylize(
    parseInput(fileContent),
  );
  for (const token of stylizedTokens) {
    switch (token.type) {
      case "paragraph":
        const content = token.content;
        const tempComponentArray: ProxiedVNode<any>[] = [];
        for (const element of content) {
          if (element.type === "image") {
            tempComponentArray.push(
              element.shouldDisplayImage
                ? Box({}, Text(element.content.render()))
                : Box({}, Text({ fg: "gray", content: element.alt })),
            );
          } else if (element.type === "text") {
            tempComponentArray.push(Text({ content: element.content }));
          } else {
            throw new Error(
              chalk.red.bold(`Did not recognize type ${element.type}`),
            );
          }
        }
        componentArray.push(Box({}, ...tempComponentArray));
        break;
      case "heading":
        // NOTE: completely generated by chatgpt
        let str = "";
        const rows = token.content.headingTextArray;
        let start = 0;
        str += "\n";
        while (start < rows[0].length) {
          let end = start;
          let lineWidth = 0;
          while (
            end < rows[0].length &&
            lineWidth + rows[0][end].length <= args.values.width
          ) {
            lineWidth += rows[0][end].length;
            end++;
          }
          for (const row of rows) {
            str += row.slice(start, end).join("");
            str += "\n";
          }
          str += "\n";
          start = end;
        }
        componentArray.push(Box({}, Text({ content: str })));
        break;
      case "table":
        const tableContent: ProxiedVNode<any>[][][] = [];
        token.content.forEach((row: ProcessedToken[]) => {
          const processedRow: ProxiedVNode<any>[][] = [];
          row.forEach((cell) => {
            processedRow.push([Text({ content: cell.content })]);
          });
          tableContent.push(processedRow);
        });
        componentArray.push(
          new TextTableRenderable(renderer, {
            width: "100%",
            wrapMode: "word",
            columnWidthMode: "content",
            columnGap: 1,
            content: tableContent as TextTableCellContent[][],
          }),
        );
        break;
      default:
        componentArray.push(Box({}, Text({ content: token.content })));
    }
  }
  return componentArray;
}

const filePath = args.positionals.at(-1);

const renderer = await createCliRenderer({
  exitOnCtrlC: true,
});

if (args.positionals.length > 2 && filePath) {
  const renderables = await renderMarkdown(filePath);
  renderer.root.add(ScrollBox({}, ...renderables));
} else {
  const fileNames = (
    await fs.readdir(".", { recursive: true, withFileTypes: true })
  )
    .filter((file) => file.isFile() && file.name.endsWith(".md"))
    .map((file) =>
      file.parentPath.length > 0
        ? [file.parentPath, file.name].join("/")
        : file.name,
    );
  const optionsArray = [];
  for (const file of fileNames) {
    let birthTime = "";
    try {
      birthTime = new Date((await fs.stat(file)).birthtime).toDateString();
    } catch (err) {
      continue;
    }
    optionsArray.push({
      name: file,
      description: `Created at: ${birthTime}`,
    });
  }
  const menu = Select({
    options: optionsArray,
    width: "100%",
    height: "100%",
    focusedBackgroundColor: "transparent",
    selectedBackgroundColor: "#181825",
    selectedTextColor: "#cdd6f4",
  });
  menu.focus();
  renderer.root.add(menu);
}
