import parseInput from "./parse-input.ts";
import stylize, { type ProcessedToken } from "./stylize.ts";
import blessed from "neo-neo-blessed";
import { parseArgs } from "node:util";
import got from "got";
import { Chalk } from "chalk";
import * as fs from "node:fs/promises";

const chalk = new Chalk();
const box = blessed.box;
const text = blessed.text;

const args = parseArgs({
  args: Bun.argv,
  options: {
    renderImages: {
      type: "boolean",
      default: true,
    },
    width: {
      type: "string",
      default: process.env.COLUMNS || "80",
    },
    printToStdout: {
      type: "boolean",
      default: false,
      short: "o",
    },
  },
  allowPositionals: true,
  allowNegative: true,
});

function renderTable(tableTokens: ProcessedToken) {
  const rows = [];
  for (const row of tableTokens.content) {
    for (const cell of row.content) {
      if (cell.type !== "table-cell") {
        throw new Error(
          chalk.red.bold(`Cell type was ${cell.type} instead of "table-cell"!`),
        );
      }
      const cells = [];
      for (const item of cell.content) {
        let cellText = "";
        if (item.type === "text") {
          if (typeof item.content !== "string") {
            throw new Error(
              chalk.red.bold(
                `The type of the table cell content was ${typeof item.content} instead of string!`,
              ),
            );
          }
          cellText += item.content;
        } else if (item.type === "image") {
          cellText += item.content.render();
        } else {
          throw new Error(
            chalk.red.bold(
              `Type not recognized: expected "text" or "image" but got ${item.type}`,
            ),
          );
        }
        cells.push(cellText);
      }
      rows.push(cells);
    }
  }
  const table = blessed.table({ rows: rows });
  return table;
}

export async function renderMarkdown(filePath: string) {
  let fileContent: string = "";
  const componentArray = [];
  if (URL.canParse(filePath)) {
    fileContent = await got(filePath).text();
  } else {
    try {
      fileContent = await Bun.file(filePath).text();
    } catch (err) {
      throw new Error(chalk.red(`Encountered an error: ${err}`));
    }
  }
  const stylizedTokens: ProcessedToken[] = await stylize(
    parseInput(fileContent),
  );
  for (const token of stylizedTokens) {
    switch (token.type) {
      case "paragraph":
        const content = token.content;
        const tempComponentArray: any[] = [];
        for (const element of content) {
          if (element.type === "image") {
            tempComponentArray.push(
              element.shouldDisplayImage
                ? blessed.text(element.content.render())
                : blessed.text({ content: chalk.gray(element.alt) }),
            );
          } else if (element.type === "text") {
            tempComponentArray.push(blessed.text({ content: element.content }));
          } else {
            throw new Error(
              chalk.red.bold(`Did not recognize type ${element.type}`),
            );
          }
        }
        componentArray.push(box({ children: tempComponentArray }));
        break;
      case "heading":
        // NOTE: completely generated by chatgpt
        let str = "";
        const rows = token.content.headingTextArray;
        let start = 0;
        str += "\n";
        while (start < rows[0].length) {
          let end = start;
          let lineWidth = 0;
          while (
            end < rows[0].length &&
            lineWidth + rows[0][end].length <= args.values.width
          ) {
            lineWidth += rows[0][end].length;
            end++;
          }
          for (const row of rows) {
            str += row.slice(start, end).join("");
            str += "\n";
          }
          str += "\n";
          start = end;
        }
        componentArray.push(text({ content: str }));
        break;
      case "table":
        componentArray.push(renderTable(token));
        break;
      default:
        componentArray.push(text({ content: token.content }));
    }
  }
  return componentArray;
}

const filePath = args.positionals.at(-1);

const screen = blessed.screen({
  smartCSR: true,
});

if (args.positionals.length > 2 && filePath) {
  const renderables = await renderMarkdown(filePath);
  screen.append(box({ children: renderables }));
} else {
  const fileNames = (
    await fs.readdir(".", { recursive: true, withFileTypes: true })
  )
    .filter((file) => file.isFile() && file.name.endsWith(".md"))
    .map((file) =>
      file.parentPath.length > 0
        ? [file.parentPath, file.name].join("/")
        : file.name,
    );
  const optionsArray: string[] = [];
  for (const file of fileNames) {
    let birthTime = "";
    try {
      birthTime = new Date((await fs.stat(file)).birthtime).toDateString();
    } catch (err) {
      birthTime = "unknown";
    }
    optionsArray.push(file.trim());
  }
  const menu = blessed.list({
    items: optionsArray,
    width: "100%",
    height: "100%",
    interactive: true,
    keys: true,
    vi: true,
    tags: true,
    invertSelected: false,
    itemHeight: 2,
    scrollable: true,
    scrollbar: {
      bg: "white",
    },
    style: {
      selected: {
        fg: "green",
      },
      item: {
        fg: "white",
      },
    },
  });
  menu.focus();
  screen.append(menu);
  // let selected = 0;
  // let offset = 0;
  // function renderMenu() {
  //   const visible = Math.floor(screen.height / 2);
  //   if (selected < offset) offset = selected;
  //   if (selected >= offset + visible) offset = selected - visible + 1;
  //   menu.setContent(
  //     fileNames
  //       .slice(offset, offset + visible)
  //       .map((file, i) => {
  //         const index = i + offset;
  //         return index === selected
  //           ? `{green-fg}${file}{/}\n{#888888-fg}Created at ${birthTimes[index]}{/}`
  //           : `${file}\n{#888888-fg}${birthTimes[index]}{/}`;
  //       })
  //       .join("\n"),
  //   );
  //   screen.render();
  // }
  // menu.key(["up", "k"], () => {
  //   if (selected > 0) {
  //     selected--;
  //     renderMenu();
  //   }
  // });
  // menu.key(["down", "j"], () => {
  //   if (selected < fileNames.length - 1) {
  //     selected++;
  //     renderMenu();
  //   }
  // });
}

screen.render();
screen.key(["C-c"], () => {
  screen.destroy();
  process.exit(0);
});
