import parseInput from "./parse-input.ts";
import stylize, { type ProcessedToken } from "./stylize.ts";
import {
  createCliRenderer,
  Box,
  Text,
  type ProxiedVNode,
  Select,
  type TextChunk,
  TextTableRenderable,
  ScrollBox,
  RGBA,
  createTextAttributes,
  StyledText,
} from "@opentui/core";
import { parseArgs } from "node:util";
import got from "got";
import { Chalk } from "chalk";
import * as fs from "node:fs/promises";
import {
  createColorPalette,
  parseAnsiSequences,
  type Color,
} from "ansi-sequence-parser";

const chalk = new Chalk();
const tableCell = (text: string): TextChunk[] => [{ __isChunk: true, text }];
const renderer = await createCliRenderer({
  exitOnCtrlC: true,
});
const colorPalette = createColorPalette();

const args = parseArgs({
  args: Bun.argv,
  options: {
    renderImages: {
      type: "boolean",
      default: true,
    },
    width: {
      type: "string",
      default: process.env.COLUMNS || renderer.width.toString() || "80",
    },
    printToStdout: {
      type: "boolean",
      default: false,
      short: "o",
    },
  },
  allowPositionals: true,
  allowNegative: true,
});

function renderTable(tableToken: ProcessedToken) {
  const rows = [];
  for (const row of tableToken.content) {
    const cells = [];
    for (const cell of row) {
      if (cell.type !== "table-cell") {
        throw new Error(
          chalk.red.bold(`Cell type was ${cell.type} instead of "table-cell"!`),
        );
      }
      for (const item of cell.content) {
        let cellText = "";
        if (item.type === "text") {
          if (typeof item.content !== "string") {
            throw new Error(
              chalk.red.bold(
                `The type of the table cell content was ${typeof item.content} instead of string!`,
              ),
            );
          }
          cellText += item.content;
        } else if (item.type === "image") {
          cellText += item.content.render();
        } else {
          throw new Error(
            chalk.red.bold(
              `Type not recognized: expected "text" or "image" but got ${item.type}`,
            ),
          );
        }
        cells.push(tableCell(cellText));
      }
      rows.push(cells);
    }
  }
  return rows;
}

export async function renderMarkdown(tokens: ProcessedToken[]) {
  const componentArray: (ProxiedVNode<any> | TextTableRenderable)[] = [];
  //#region
  for (const token of tokens) {
    //#region switch token type
    switch (token.type) {
      //#region paragraph
      case "paragraph":
        const content = token.content;
        const tempComponentArray = [];
        for (const element of content) {
          if (element.type === "image") {
            tempComponentArray.push(
              element.shouldDisplayImage
                ? Text({ content: element.content.render() })
                : Text({ content: chalk.gray(element.alt) }),
            );
          } else if (element.type === "text") {
            const parsedAnsi = parseAnsiSequences(element.content);
            const textRenderables: TextChunk[] = [];
            parsedAnsi.forEach((ansiToken) =>
              textRenderables.push({
                __isChunk: true,
                text: ansiToken.value,
                fg: ansiToken.foreground
                  ? "name" in ansiToken.foreground
                    ? RGBA.fromHex(colorPalette.value(ansiToken.foreground))
                    : "rgb" in ansiToken.foreground
                      ? RGBA.fromValues(...ansiToken.foreground.rgb)
                      : undefined
                  : undefined,
                bg: ansiToken.background
                  ? "name" in ansiToken.background
                    ? RGBA.fromHex(colorPalette.value(ansiToken.background))
                    : "rgb" in ansiToken.background
                      ? RGBA.fromValues(...ansiToken.background.rgb)
                      : undefined
                  : undefined,
                attributes: createTextAttributes({
                  bold: ansiToken.decorations.has("bold"),
                  italic: ansiToken.decorations.has("italic"),
                  underline: ansiToken.decorations.has("underline"),
                  dim: ansiToken.decorations.has("dim"),
                  strikethrough: ansiToken.decorations.has("strikethrough"),
                }),
              }),
            );
            tempComponentArray.push(
              Text({ content: new StyledText(textRenderables) }),
            );
          } else {
            throw new Error(`Did not recognize type ${element.type}`);
          }
        }
        componentArray.push(Box({}, ...tempComponentArray));
        break;
      //#endregion
      //#region heading
      case "heading":
        // NOTE: completely generated by chatgpt
        let str = "";
        const rows = token.content.headingTextArray;
        let start = 0;
        str += "\n";
        while (start < rows[0].length) {
          let end = start;
          let lineWidth = 0;
          while (
            end < rows[0].length &&
            lineWidth + rows[0][end].length <= args.values.width
          ) {
            lineWidth += rows[0][end].length;
            end++;
          }
          for (const row of rows) {
            str += row.slice(start, end).join("");
            str += "\n";
          }
          str += "\n";
          start = end;
        }
        componentArray.push(Text({ content: str }));
        break;
      //#endregion
      //#region table
      case "table":
        componentArray.push(
          new TextTableRenderable(renderer, { content: renderTable(token) }),
        );
        break;
      //#endregion
      //#region bullet list
      case "bullet_list":
        const bp = "\u2022";
        const bulletListItems = [];
        for (const listItem of token.content as ProcessedToken[]) {
          if (listItem.type !== "list_item")
            throw new Error(
              chalk.red.bold(
                `Expected type "list_item" but got ${listItem.type}`,
              ),
            );
          const listRenderables = await renderMarkdown(listItem.content);
          for (const listRenderable of listRenderables) {
            bulletListItems.push(
              Box(
                {
                  flexDirection: "row",
                  gap: 1,
                  margin: 0,
                  padding: 0,
                },
                Text({ content: bp }),
                Box({}, listRenderable),
              ),
            );
          }
        }
        componentArray.push(Box({}, ...bulletListItems));
        break;
      //#endregion
      //#region ordered list
      case "ordered_list":
        let number = token.properties.start || 1;
        const orderedListItems = [];
        for (const listItem of token.content as ProcessedToken[]) {
          if (listItem.type !== "list_item")
            throw new Error(
              chalk.red.bold(
                `Expected type "list_item" but got ${listItem.type}`,
              ),
            );
          const listRenderables = await renderMarkdown(listItem.content);
          for (const listRenderable of listRenderables) {
            orderedListItems.push(
              Box(
                {
                  flexDirection: "row",
                  gap: 1,
                  margin: 0,
                  padding: 0,
                },
                Text({ content: `${number}.` }),
                Box({}, listRenderable),
              ),
            );
            number++;
          }
        }
        componentArray.push(Box({}, ...orderedListItems));
        break;
      //#endregion
      //#region default
      default:
        const parsedAnsi = parseAnsiSequences(String(token.content));
        const textRenderables: TextChunk[] = [];
        parsedAnsi.forEach((ansiToken) =>
          textRenderables.push({
            __isChunk: true,
            text: ansiToken.value,
            fg: ansiToken.foreground
              ? "name" in ansiToken.foreground
                ? RGBA.fromHex(colorPalette.value(ansiToken.foreground))
                : "rgb" in ansiToken.foreground
                  ? RGBA.fromValues(...ansiToken.foreground.rgb)
                  : undefined
              : undefined,
            bg: ansiToken.background
              ? "name" in ansiToken.background
                ? RGBA.fromHex(colorPalette.value(ansiToken.background))
                : "rgb" in ansiToken.background
                  ? RGBA.fromValues(...ansiToken.background.rgb)
                  : undefined
              : undefined,
            attributes: createTextAttributes({
              bold: ansiToken.decorations.has("bold"),
              italic: ansiToken.decorations.has("italic"),
              underline: ansiToken.decorations.has("underline"),
              dim: ansiToken.decorations.has("dim"),
              strikethrough: ansiToken.decorations.has("strikethrough"),
            }),
          }),
        );
        componentArray.push(Text({ content: new StyledText(textRenderables) }));
      //#endregion
    }
    //#endregion
  }
  //#endregion
  return componentArray;
}

const fileNames = (
  await fs.readdir(".", { recursive: true, withFileTypes: true })
)
  .filter((file) => file.isFile() && file.name.endsWith(".md"))
  .map((file) =>
    file.parentPath.length > 0
      ? [file.parentPath, file.name].join("/")
      : file.name,
  );
const optionsArray = [];
for (const file of fileNames) {
  let birthTime = "";
  try {
    birthTime = new Date((await fs.stat(file)).birthtime).toDateString();
  } catch (err) {
    birthTime = "unknown";
  }
  optionsArray.push({ name: file, description: `Created at: ${birthTime}` });
}
const menu = Select({
  options: optionsArray,
  width: "100%",
  height: "100%",
});

if (args.positionals.length > 2) {
  const filePath = args.positionals.at(-1);
  let fileContent = "";
  if (URL.canParse(filePath!)) {
    fileContent = await got(filePath!).text();
  } else {
    try {
      fileContent = await Bun.file(filePath!).text();
    } catch (err) {
      throw new Error(`Encountered an error: ${err}`);
    }
  }
  const tokens = await stylize(parseInput(fileContent));
  const renderables = await renderMarkdown(tokens);
  const box = ScrollBox({ rowGap: 1 }, renderables);
  box.focus();
  renderer.root.add(box);
} else {
  menu.focus();
  renderer.root.add(menu);
}
