import {
  Box,
  createCliRenderer,
  ScrollBox,
  Text,
  type ProxiedVNode,
} from "@opentui/core";
import chalk from "chalk";
import got from "got";
import stylize, { type ProcessedToken } from "./stylize";
import parseInput from "./parse-input.ts";
import { parseArgs } from "node:util";

const args = parseArgs({
  args: Bun.argv,
  options: {
    renderImages: {
      type: "boolean",
      default: true,
    },
    width: {
      type: "string",
      default: process.env.COLUMNS || "80",
    },
  },
  allowPositionals: true,
  allowNegative: true,
});

export async function renderMarkdown(filePath: string) {
  let fileContent: string = "";
  const componentArray: ProxiedVNode<any>[] = [];
  if (URL.canParse(filePath)) {
    fileContent = await got(filePath).text();
  } else {
    try {
      fileContent = await Bun.file(filePath).text();
    } catch (err) {
      throw new Error(chalk.red(`Encountered an error: ${err}`));
    }
  }
  const stylizedTokens: ProcessedToken[] = await stylize(
    parseInput(fileContent),
  );
  for (const token of stylizedTokens) {
    switch (token.type) {
      case "paragraph":
        const content = token.content;
        const tempComponentArray: ProxiedVNode<any>[] = [];
        for (const element of content) {
          if (element.type === "image") {
            tempComponentArray.push(
              element.shouldDisplayImage
                ? Box({}, Text(element.content.render()))
                : Box({}, Text({ fg: "gray", content: element.alt })),
            );
          } else if (element.type === "text") {
            tempComponentArray.push(Text({ content: element.content }));
          } else {
            throw new Error(
              chalk.red.bold(`Did not recognize type ${element.type}`),
            );
          }
        }
        componentArray.push(Box({}, ...tempComponentArray));
        break;
      case "heading":
        // NOTE: completely generated by chatgpt
        let str = "";
        const rows = token.content.headingTextArray;
        let start = 0;
        str += "\n";
        while (start < rows[0].length) {
          let end = start;
          let lineWidth = 0;
          while (
            end < rows[0].length &&
            lineWidth + rows[0][end].length <= args.values.width
          ) {
            lineWidth += rows[0][end].length;
            end++;
          }
          for (const row of rows) {
            str += row.slice(start, end).join("");
            str += "\n";
          }
          str += "\n";
          start = end;
        }
        componentArray.push(Box({}, Text({ content: str })));
        break;
      default:
        componentArray.push(Box({}, Text({ content: String(token.content) })));
    }
  }
  return componentArray;
}

const renderer = await createCliRenderer({ exitOnCtrlC: true });
const renderables = await renderMarkdown("../test-files/all.md");
renderer.root.add(ScrollBox({}, ...renderables));
